const menu = [
 
  {
    id: 1,
    title: 'Egg Attack',
    category: 'Latest shows',
    img: 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/05/eggs-counter-1296x728-header.jpg?w=1155&h=1528',
    desc: `@4ygfrt8...`,
    desc1:'09hy5dg...',},
  {
    id: 2,
    title: 'Dream',
    category: 'Latest shows',
    img: 'https://media.istockphoto.com/photos/3d-render-abstract-geometric-background-white-cloud-and-glowing-neon-picture-id1305282477?b=1&k=20&m=1305282477&s=170667a&w=0&h=-TRTm0TlXK0WP55ZlC7MaxRyEY7OUj2QziYCkNfpx-8=',
    desc: `@6yfrg43f...`,
    desc1:'yurt54f...',},
  {
    id: 3,
    title: 'Bacon ',
    category: 'Latest shows',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5kPstaFtTgu3Ww0ehQuU_kU7KQsvmb88KLA&usqp=CAU',
    desc: `@34rc6tf...`,
    desc1:'563dfe3...', },
  {
    id: 4,
    title: 'American classic',
    category: 'Latest shows',
    img: 'https://www.hollywoodreporter.com/wp-content/uploads/2015/09/friends_still_ok_-_h_2015_0.jpg?w=681&h=383&crop=1',
    desc: `@gv56det...`,
    desc1:'7frx45h...',},
  {
    id: 5,
    title: 'Wild',
    category: 'Most Popular',
    img: 'https://i.guim.co.uk/img/media/c0e411f5b4c387cd8b275f0794a3618210c5b216/0_339_5081_3048/master/5081.jpg?width=465&quality=45&auto=format&fit=max&dpr=2&s=65cb0f7e2f7e906f92336bcb5c0fa6bb',
    desc: `@t67hf89...`,
    desc1:'yugjhf...',},
    {
    id: 6,
    title: 'Quarantine',
    category: 'Most Popular',
    img: 'https://media-cldnry.s-nbcnews.com/image/upload/newscms/2020_49/3432584/201202-woman-quarantine-se-1103a.jpg',
    desc: `@tvef89...`,
    desc1:'yugjhf...',},
    {
      id: 7,
       title: 'Movies',
      category: 'Most Popular',
      img: 'https://media.istockphoto.com/photos/pop-corn-and-on-red-armchair-cinema-picture-id1271522601?b=1&k=20&m=1271522601&s=170667a&w=0&h=azZRRchShbrwRgq58omc1HOYABnfDDOzXJatuaZrueQ=',
      desc: `@tvef89...`,
      desc1:'yugjhf...',},
      {
        id: 8,
        title: 'Sugar',
        category: 'Most Popular',
        img: 'https://www.ledgerinsights.com/wp-content/uploads/2020/10/sugar.2-810x476.jpg',
        desc: `@tvef89...`,
        desc1:'yugjhf...',},
        {
        id: 9,
        title: 'leg bar',
        category: '💎In Genesis',
        img: 'https://images.unsplash.com/photo-1531210488748-d1620f6506a5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8c2hhdmVkJTIwbGVnc3xlbnwwfHwwfHw%3D&w=1000&q=80',
        desc: '@3456hhf...',
        desc1:'yugjhf...',
        },
       {
        id: 10,
        title: 'Mad House',
        category: '💎In Genesis',
        img: 'https://media.architecturaldigest.com/photos/569992ccc6772b76145675a2/16:9/w_2580,c_limit/retreat-the-modern-house-in-nature-01.jpg',
        desc: `@0hty65i...`,
        desc1:'ugre8y...',
      },
      {
        id: 11,
        title: ' Milkshake',
        category: '💎In Genesis',
        img: 'https://bakingmischief.com/wp-content/uploads/2022/03/coffee-milkshake-square.jpg',
        desc: `@yt5fde8...`,
        desc1:'65fr34...',
      },
      {
        id: 12,
        title: 'Country',
        category: '💎In Genesis',
        img: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/colors-of-italy-series-manarola-village-cinque-royalty-free-image-1622081263.jpg',
        desc: `@ihy65hf...`,
        desc1:'9ygt5h...',
      },
      {
        id: 13,
        title: 'Karnataka',
        category: '🛕In Temple',
        img: 'https://www.karnatakatourism.org/wp-content/uploads/2020/05/Vidyashankara-Temple.jpg',
        desc: '@3456hhf...',
        desc1:'yugjhf...',
        },
       {
        id: 14,
        title: 'Tamil Nadu',
        category: '🛕In Temple',
        img: 'https://tourismtn.com/wp-content/uploads/2020/11/Masani-Amman-Temple.jpg',
        desc: `@0hty65i...`,
        desc1:'ugre8y...',
      },
      {
        id: 15,
        title: 'West Bengal',
        category: '🛕In Temple',
        img: 'https://im.whatshot.in/img/2020/Sep/15225-d-1599158297.jpg',
        desc: `@yt5fde8...`,
        desc1:'65fr34...',
      },
      {
        id: 16,
        title: 'Chennai',
        category: '🛕In Temple',
        img: 'https://img.traveltriangle.com/blog/wp-content/uploads/2018/01/Ekambareswarar-Temple-kb6592.jpg',
        desc: `@ihy65hf... `,
        desc1:'9ygt5h...',
      },
      {
        id: 17,
        title: 'Dance',
        category: '🦅In Void',
        img: 'https://img.freepik.com/free-photo/full-length-portrait-jumping-white-girls-expressing-happy-emotions-portrait-best-friends-funny-dancing-together_197531-10953.jpg?size=626&ext=jpg&ga=GA1.2.1946062945.1642118400',
        desc:'@t6fuv09...',
        desc1:'yugjhf...',
        },
       {
        id: 18,
        title: 'Vintage',
        category: '🦅In Void',
        img: 'https://photographycourse.net/wp-content/uploads/2020/05/man-taking-photo-of-person-in-water.jpg',
        desc: `@0hty65i...`,
        desc1:'ugre8y...',
      },
      {
        id: 19,
        title: ' Old',
        category: '🦅In Void',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoROPDtYUMINsYENfXqOhf2ZydHw4o_zr3HFx8R1kPOPegQR1liUkMb7ZKf7vjJKgtLq0&usqp=CAU',
        desc: `@yt5fde8...`,
        desc1:'65fr34...',
      },
      {
        id: 20,
        title: 'Smile',
        category: '🦅In Void',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZk89QZHPb3WAKxV7BCvdXR3wJ4rqewQfZwQ&usqp=CAU',
        desc: `@ihy65hf... `,
        desc1:'9ygt5h...',
      },
      {
        id: 21,
        title: 'Panda',
        category: '🦍#BAYC',
        img: 'https://ychef.files.bbci.co.uk/976x549/p08gfs3y.jpg',
        desc: '@3456hhf...',
        desc1:'w34rf0...',
        },
       {
        id: 22,
        title: 'Squirel',
        category: '🦍#BAYC',
        img: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/BB1dH1E7.img?h=552&w=750&m=6&q=60&u=t&o=f&l=f',
        desc: `@76bht50...`,
        desc1:'Ec54gj...',
      },
      {
        id: 23,
        title: ' Dog',
        category: '🦍#BAYC',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSw9yjCgv1aVt9SDWTNzxz8SC2gSjvUJwnbUQ&usqp=CAU',
        desc: `@yter4e8...`,
        desc1:'6bd8b4j...',
      },
      {
        id: 24,
        title: 'Toucan',
        category: '🦍#BAYC',
        img: 'https://cdn2.outdoorphotographer.com/2019/06/telephoto-wildlife-technique-feat-481x305.jpg',
        desc: `@h65r5ih... `,
        desc1:'hbrur5...',
      },
];
export default menu;